[package]
name = "pop-upgrade-client"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
enumflags2 = "0.7.12"
futures = "0.3.32"
num-derive = "0.4.2"
num-traits = "0.2.19"
serde = "1.0.228"
serde_repr = "0.1.20"
tokio.workspace = true
zbus = "5.16.0"
zvariant = "5.12.0"

[dev-dependencies]
tokio = { workspace = true, features = ["rt"]}
