[package]
name = "pop-system-updater"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
ron = "0.12.1"
serde = { version = "1.0.0", features = ["derive"] }
serde_repr = "0.1.20"
tokio = { workspace = true, features = ["fs"] }
zbus = "5.0.0"
zvariant = { version = "5.0.0", features = ["enumflags2"] }
