[package]
name = "cosmic-settings-system"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = { version = "4.0.18", default-features = false }
const_format = "0.2.30"
concat-in-place = "1.1.0"
sysinfo = "0.27.7"
memchr = "2.5.0"

[dependencies.bumpalo]
version = "3.12.0"
features = ["collections"]
